# Generated by Django 3.1.4 on 2020-12-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todos',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
