# Generated by Django 3.1.4 on 2020-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20201213_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
